# IssieSign versions
issiesign.versionCode=10112
issiesign.versionName=2.2.3

# IssieSignArabic versions
issiesignarabic.versionCode=10105
issiesignarabic.versionName=2.2.3

# IssieSign iOS versions (versionName = MARKETING_VERSION, versionCode = CURRENT_PROJECT_VERSION)
issiesign.ios.versionName=2.5.1
issiesign.ios.versionCode=11
